### PR TITLE
feat(perception): Perception node created

### PR DESCRIPTION
**Pull request by Davide64-dev**

### CODE REVIEW

**Comment by marhcouto** [comment]
Task linked: [CU-8693hqewb Create C++ Perception Node](https://app.clickup.com/t/8693hqewb)

**Review by marhcouto — CHANGES_REQUESTED** [review]
I know I said I had already reviewed but now it occurred to me that it would be nice to separate the main function from the executable code of the node, putting this part in an equivalent cpp to the hpp created. This would improve testability

**Review by marhcouto — APPROVED** [review]
Nice work

**Review by BrunoDias201907828 — APPROVED** [review]
Everything worked perfectly, good job

**Pull request merged**
